version: 2
jobs:
  build:
    working_directory: ~/aemon
    docker:
      - image: node:6.11.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ arch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ arch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run: npm test
      - run: |
          ./cc-test-reporter before-build
          sudo vendor/bin/phpunit --coverage-clover clover.xml
      - run: npm run test:cover
      - run: |
          ./cc-test-reporter after-build --coverage-input-type clover --exit-code $?

